# Generated by Django 4.2.4 on 2024-02-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateuser',
            name='breakstart_holi',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dateuser',
            name='finishwork_holi',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dateuser',
            name='startwork_holi',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dateuser',
            name='timebreak_holi',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldateuser',
            name='breakstart_holi',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldateuser',
            name='finishwork_holi',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldateuser',
            name='startwork_holi',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldateuser',
            name='timebreak_holi',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
