# Generated by Django 4.2.4 on 2024-02-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_dateuser_breakstart_holi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateuser',
            name='timebreak_holi',
        ),
        migrations.RemoveField(
            model_name='historicaldateuser',
            name='timebreak_holi',
        ),
    ]
