# Generated by Django 4.2.4 on 2024-02-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_dateuser_timebreak_holi_and_more'),
    ]

    operations = [
    ]
