# Generated by Django 4.2.4 on 2024-02-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20240221_1654'),
    ]

    operations = [
    ]
