# Generated by Django 4.2.4 on 2024-02-21 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0005_auto_20240221_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateuser',
            name='foreinguser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Pro'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='foreinguser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Pro'),
        ),
    ]
